version: '2'
services:

 postgres:
   image: postgres:9.6
   ports:
     - "54324:54324"
   environment:
     - POSTGRES_DB=POSTGRESQL
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=root
     - MAX_CONNECTIONS=300