CREATE TABLE IF NOT EXISTS configuracao (

  codigo  BIGINT PRIMARY KEY  NOT NULL,
  chave   VARCHAR(100) UNIQUE,
  valor   VARCHAR(400)

);

CREATE SEQUENCE IF NOT EXISTS configuracao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

INSERT INTO configuracao(codigo, chave, valor)
VALUES(nextval('configuracao_seq'), 'PERMISSOES_BASICAS', 'ROLE_PESQUISAR_AGENDAMENTO;ROLE_CADASTRAR_AGENDAMENTO;' ||
 'ROLE_REMOVER_AGENDAMENTO;ROLE_PESQUISAR_FUNCIONARIO;ROLE_CADASTRAR_FUNCIONARIO;ROLE_REMOVER_FUNCIONARIO;' ||
  'ROLE_PESQUISAR_HORARIO;ROLE_TROCA_SENHA;ROLE_UPLOAD_ARQUIVO');