CREATE TABLE IF NOT EXISTS aptidao (

  codigo            BIGINT PRIMARY KEY  NOT NULL,
  apto              BOOLEAN NOT NULL DEFAULT  FALSE,
  tipoAptidao       VARCHAR(255)

);

CREATE SEQUENCE IF NOT EXISTS aptidao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;